### ISSUE TITLE
Annotate Venn diagram

### ISSUE THREAD

**Issue by anuragnsharma** [yanlinlin82/ggvenn#19]
Apart from the standard venn diagram plot:

- How would I add separate labels within and outside the overlap areas?
- Can there be a possibility of doing this similar to what ggrepel does?
- Are you planning to add a scaling functionality where the size of overlap and circles scales to the number of the elements being represented?
- How do I change the font of the text, how would I do it separately for the set names and within the venn diagram?

Fantastic package btw! This has been missing for a while for ggplot2.

**Comment by yanlinlin82** [comment]
Hi @anuragnsharma ,

Thanks for your interest in ggvenn.

Since ggvenn is based on ggplot, it is easy to add separate labels:

```r
library(ggvenn)
g <- list(A = 1:3, B = 2:5) %>% ggvenn()
g + geom_label(data = tibble(x = -1:1, y = -1, s = c("aaa", "bbb", "ccc")), aes(x, y, label = s))
```

or with ggrepel:

```r
library(ggrepel)
g + geom_label_repel(data = tibble(x = 0, y = -1, s = c("aaa", "bbb", "ccc")), aes(x, y, label = s))
```

For the third question, the answer is yes. I am thinking about how to implement the scaling features, and maybe I will try it in the next two or three months.

For the last question, changing the font of set names and texts, so far there is no good way to customize them because I hard-coded that in ggvenn. I will consider this requirement in the future.

**Comment by anuragnsharma** [comment]
Great! Looking forward to the upcoming additions.
